### ISSUE TITLE
Not working in MacVim

### ISSUE THREAD

**Issue by narath** [itspriddle/vim-marked#29]
Very cool plugin. Thanks for developing it.

I am able to get this to work in Vim when launched from the console, but not when trying to use it within MacVim. I'm on Custom Version 8.1.950 (155)

**Comment by itspriddle** [comment]
Hey @narath, thanks 😊 !

By not working, do you mean that the `:MarkedOpen` command and others aren't available when you are editing a markdown buffer in MacVim? Or is there an issue with opening Marked itself?

It might also be the case that MacVim isn't setting the right filetype. Can you open a markdown file and try `:echo &ft` from MacVim? It should be one of `["markdown", "mkd", "ghmarkdown", "vimwiki"]`

**Comment by narath** [comment]
Hey @itspriddle - thanks for getting back to me. It seems to be working now. 

The error I was getting was "Not an editor command: MarkedOpen"

I think that I might have restarted Marked2 so perhaps it was initially recognized by the plugin.

Really appreciate the plugin.
