### ISSUE TITLE
MarkedToggle suspends the vim process in terminal vim

### ISSUE THREAD

**Issue by engeljh** [itspriddle/vim-marked#31]
Everything works fine in gvim, but when I try to toggle or open marked in terminal vim, the vim process is suspended and I'm kicked out to the shell.

**Comment by itspriddle** [comment]
Can you supply the output of `vim --version` and your Marked.app version please? 

Also, what was the full file path you were trying this with? I doubt it is the cause of what you are describing, but I do recall having issues with paths containing special chars.

**Comment by engeljh** [comment]
Hi,

Thanks, here's the info you asked for:

Output of vim --version

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Sep 12 2023 09:31:27)
macOS version - arm64
Included patches: 1-1897
Compiled by GitHub Actions
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl                +find_in_path       +mouse_xterm        -tcl
+arabic             +float              +multi_byte         +termguicolors
+autocmd            +folding            +multi_lang         +terminal
+autochdir          -footer             -mzscheme           +terminfo
-autoservername     +fork()             +netbeans_intg      +termresponse
+balloon_eval       +fullscreen         +num64              +textobjects
+balloon_eval_term  +gettext            +odbeditor          +textprop
+browse             -hangul_input       +packages           +timers
++builtin_terms     +iconv              +path_extra         +title
+byte_offset        +insert_expand      +perl/dyn           +toolbar
+channel            +ipv6               +persistent_undo    +transparency
+cindent            +job                +popupwin           +user_commands
+clientserver       +jumplist           +postscript         +vartabs
+clipboard          +keymap             +printer            +vertsplit
+cmdline_compl      +lambda             +profile            +vim9script
+cmdline_hist       +langmap            +python/dyn         +viminfo
+cmdline_info       +libcall            +python3/dyn-stable +virtualedit
+comments           +linebreak          +quickfix           +visual
+conceal            +lispindent         +reltime            +visualextra
+cryptv             +listcmds           +rightleft          +vreplace
+cscope             +localmap           +ruby/dyn           +wildignore
+cursorbind         +lua/dyn            +scrollbind         +wildmenu
+cursorshape        +menu               +signs              +windows
+dialog_con_gui     +mksession          +smartindent        +writebackup
+diff               +modify_fname       +sodium             -X11
+digraphs           +mouse              +sound              -xfontset
+dnd                +mouseshape         +spell              +xim
-ebcdic             +mouse_dec          +startuptime        -xpm
+emacs_tags         -mouse_gpm          +statusline         -xsmp
+eval               -mouse_jsbterm      -sun_workshop       -xterm_clipboard
+ex_extra           +mouse_netterm      +syntax             -xterm_save
+extra_search       +mouse_sgr          +tag_binary
-farsi              -mouse_sysmouse     -tag_old_static
+file_in_path       +mouse_urxvt        -tag_any_white
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe -DMACOS_X -DMACOS_X_DARWIN -g -O2 -arch x86_64 -arch arm64 -I/usr/local/Cellar/libsodium/1.0.18_1/include -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wall -Wextra -Wshadow -Werror -Wno-deprecated-declarations -Wno-error=missing-field-initializers -Wno-error=deprecated-declarations -Wno-error=unused-function
Linking: clang -arch x86_64 -arch arm64 -L/usr/local/lib -o Vim -lm -lncurses /usr/local/lib/libsodium.a -liconv /usr/local/lib/libintl.a -framework AppKit

Marked.app version 2.6.25

Path: any path, but in particular /Users/jon/file.md
________________________________

**Comment by itspriddle** [comment]
Can you try running `:!open -a 'Marked 2' '/Users/jon/file.md'` from within Vim?

Does this open Marked with your document, or do you see the same behavior?

**Comment by engeljh** [comment]
That does the same thing: opens Marked and suspends my vim session.

I can get back into the vim session with Marked open by typing 'fg', so this situation is not dire.  Just thought it might be straightforward to fix.
________________________________

**Comment by itspriddle** [comment]
If you run `:set shellcmdflag?` is it returning `shellcmdflag=-ic` by chance?

**Comment by engeljh** [comment]
Nope, it returns shellcmdflag=-c .
________________________________

**Comment by itspriddle** [comment]
Please try the latest version which now uses `open x-marked://` URIs behind the scenes. Feel free to reopen if you're still having issues.
